sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5-dev"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=netius setup.py test
after_success: coveralls
notifications:
  slack: hivesolutions:838m5XXohsuxjWI0mSzghWOK
deploy:
  provider: pypi
  user: joamag
  password:
    secure: gzWBCLnONawEYAtR3S/PlxizOXuNxA0wOQQExxS6TempCNGX1Z7DwixDxt6V7LDFI38ow/XsEOUu8L6MHLCWGbUqbwZz6kS9w2RPT1Jtzi8wwCx25K6LDxmBgg0qIDJ9F8tfJd2SnZme3vtEfgglA3MMNFPI5vNA8e1qmZGzvBE=    
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
